Update clouds.md
metallb/metallb pull request #2640
Opened 2024-12-18 01:50 UTC by robkooper

update openstack notes

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
/kind documentation
> /kind regression

**What this PR does / why we need it**:

This describes how we use metallb in openstack without having to disable arp spoofing. This is done by adding the ip addresses from the pool as allowed addresses in openstack. (see https://docs.openstack.org/developer/dragonflow/specs/allowed_address_pairs.html).

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2025-01-24 10:15 UTC, fedepaol commented
@robkooper mind signing the commit?

2025-01-24 14:03 UTC, EmilienM commented on website/content/installation/clouds.md
> +You can  disable OpenStack's ARP spoofing protection if you want to
```suggestion
You can disable OpenStack's ARP spoofing protection if you want to
```

2025-01-24 14:03 UTC, EmilienM commented on website/content/installation/clouds.md
> +You can  disable OpenStack's ARP spoofing protection if you want to
to disable spoofing protection, you can mention that port security needs to be disabled on the Neutron port.

2025-01-24 14:04 UTC, EmilienM requested changes
minor comments but otherwise looks good, thanks!

2025-02-14 09:04 UTC, fedepaol commented
@robkooper mind applying the suggested changes / signing the commit? Thanks!

2025-03-28 00:04 UTC, closed without merging