Do not set resources limits by default
metallb/metallb pull request #765
Opened 2020-10-24 21:25 UTC by champtar

I've experienced issues in the past where MetalLB was throttled
for 15s and then replying to all previous ARP request at the same time.
MetalLB is the entry point of the cluster, if it's not working everything
else in the cluster is useless, so let's just not set limits.

2020-10-28 14:43 UTC, champtar commented on manifests/metallb.yaml
> -            cpu: 100m
memory I'm open, CPU you can't debug without a tcpdump ...

2021-03-15 14:20 UTC, champtar commented
@daxmc99 @johananl @rata any opinions

2021-03-26 19:56 UTC, russellb requested changes
I prefer this change where we remove the limits by default.  I don't think the lines need to remain commented out though.  I'd just remove them.

2021-03-26 20:20 UTC, champtar commented
Updated and rebased

2021-03-26 21:17 UTC, russellb approved these changes
Thanks!  I think this is the right default, and we'll just need to document it in our release notes that it changed.

2021-03-26 21:17 UTC, merged

2021-06-25 08:00 UTC, ohauer commented
Removing the resorces results in the containesrs running only with best effort and is something you really don't want to have on a cluster with high load.
Wouldn't it be better to set additional requests to reserve CPU and memory to avoid such situations?
E.g. I'm using this values on a high load dev cluster with arp and in another location with bgb.

```yaml
resources:
  limits:
    cpu: 150m
    memory: 128Mi
  requests:
    cpu: 15m
    memory: 56Mi
```

From inspecting the speakers I see in idle they use ~ 40Mi Ram and 5-10m core, on load memory goes a littel bit higher but even on a system where I inject 10 services at one time load goes not over 120m core.
Additional side effect, with the complete removal it is hard to patch in the values with kustomize.

2021-06-25 14:48 UTC, russellb commented
Thanks for the feedback. I'd be OK putting in resource requests by default, but would leave out limits.